name: Hello Flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World!"
      - name: Diga value
        run: echo "Value - bye!"
